function GinzburgLandauODESolver

%The following code provides a numerical solution to the time independent
%Ginzburg-Landau ODE where the ODE is defined within the function defined
%on line 80. 

tstart = 0;
tend = 10^2; 

NumSteps = 10^3;
tspan = linspace(tstart, tend, NumSteps);

%The parameters below are epsilon, kappa, eta, and q'not', respectively
%which are parameters in the ODE as well as those used in the Lyapunov
%functions designed for the associated equilibrium points.

e = 1; 
k = 0.5; 
n = 1; 
q0 = 0.51;

%The following three functions are original Lyapunov functions designed to
%determine the stability of the steady states. In this code, we are
%attempting to determine the interaction of these functions, if there is
%any, within the intersection of their corresponding domains. 

V0 = @(f,q) (k^2*f.^2).*(1-(f.^2+((q.^2)*(n+e))/(n*k^2)));
V1 = @(f,q) (f.^2).*(k^2*(f+1)-k^2*(f.^2+((q.^2)*(n+e))/(n*k^2)))+f*(q.^2-k^2);
Vq0 = @(f,q) (k^2*f.^2)*(1-(f.^2+((n+e)*q.^2-e*q*q0)/(n*k^2)));


%The following six parameters are simply to control the two 'for loops'
%found below. 

a = -2; 
b = 2; 
c = 1; 

d = -2; 
g = 2; 
L = 1; 

alpha = (b-a)/c +1; 
beta = (g-d)/L +1;

A = zeros(3, alpha*beta);
points = strings(1, alpha*beta);

counter = 0; 

%This 'for loop' is designed to produce a table comparing the value of the
%designed Lyapunov functions for various initial conditions.

for F = a:c:b
    for Q = d:L:g
        counter=counter+1;

        A(1,counter) = V0(F,Q);
        A(2,counter) = V1(F,Q);
        A(3,counter) = Vq0(F,Q);

        str = sprintf('(%.1f, %.1f)', F,Q);
        name = string(str);
        points(counter) = name;

    end
end

T = array2table(A);
allVars = 1:width(T);
T = renamevars(T,allVars,points)

%The following 'for loop' is meant to produce the phase portrait of the
%ODE.

for i = a:c:b
    for j = d:L:g

    xinit = [i j];

    [t, x] = ode45(@PhaseLockEquations, tspan, xinit); 

    f = x(:,1);
    q = x(:,2);

    plot(f, q);
    hold on
    xlabel('f');
    ylabel('q');
    end

xlim([a b])
ylim([d g])
end

hold off


function dxdt = PhaseLockEquations(t,x)

%Near the critical temperature Tc, type one superconductors have k <
%1/sqrt(2) whilest type two superconductors have k > 1/sqrt(2). 

    k = 0.5; 
    n = 1; 

%In this block, we define a forcing function, that is, an external magnetic
%field with respect to a superconductor which is generated by an a current 
%carrying wire. Observe that h1 represents a forcing function from a direct
%current whilst h2 is a result of an alternating current. 

    mu0 = 1.25663706127*10^(-6);
    imax = 10;
    R = 10^(-4); 
    A = (mu0*imax)/(2*pi*R);
    DC = 0;

    h1 = A*DC;
    h2 = A*sin(60*t);

    f = x(1);
    q = x(2);

    dxdt = zeros(size(x));

    dxdt(1) = k^2*(1-f^2)*f-(q^2)*f;
    dxdt(2) = (1/n)*h2-(1/n)*(f^2)*q; 

    end

end